/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 일반 회원가입 (이메일/비밀번호) */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 일반 로그인 (이메일/비밀번호) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 카카오 OAuth 로그인/회원가입 */
        post: operations["AuthController_kakaoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 애플 OAuth 로그인/회원가입 (iOS 필수) */
        post: operations["AuthController_appleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 구글 OAuth 로그인/회원가입 */
        post: operations["AuthController_googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access Token 재발급 (자동 로그인) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 (refreshToken 무효화) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 회원탈퇴 */
        delete: operations["AuthController_withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** [관리자] 전체 자격증 검수 목록 */
        get: operations["CertificationsController_findAll"];
        put?: never;
        /** 자격증/졸업증명서 첨부 및 검수 요청 */
        post: operations["CertificationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certifications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 자격증 검수 목록 조회 */
        get: operations["CertificationsController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certifications/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** [관리자] 자격증 검수 상태 변경 */
        patch: operations["CertificationsController_updateStatus"];
        trace?: never;
    };
    "/home/expert-grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 명인 홈: 명인등급 조회 (리뷰수/별점/등급) */
        get: operations["HomeController_getExpertGrade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/review-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 명인 홈: 리뷰 요청 링크 생성 (카카오 딥링크) */
        post: operations["HomeController_createReviewRequestLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/diagnosis-requests/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 명인 홈: 요청진단 미리보기 (신청순 최대 3개) */
        get: operations["HomeController_getDiagnosisPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 홈: 명인/고객 모드 전환 */
        patch: operations["HomeController_switchMode"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResponseDto: {
            /** @description 응답 페이로드 */
            data: Record<string, never>;
        };
        AuthUserDto: {
            /**
             * @description 유저 ID
             * @example 1
             */
            id: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 이름
             * @example 김운동
             */
            name: string;
            /**
             * @description 개인 코드
             * @example USR-000001
             */
            personalCode: string;
            /**
             * @description 현재 모드
             * @example customer
             * @enum {string}
             */
            currentMode: "expert" | "customer";
            /**
             * @description 소셜 제공자
             * @example local
             * @enum {string}
             */
            socialProvider: "local" | "kakao" | "apple" | "google";
            /**
             * @description 모드를 명시적으로 확정했는지 여부(false면 모드선택 필요)
             * @example true
             */
            hasSelectedMode: boolean;
            /**
             * @description 자격증 이미지 업로드 여부
             * @example false
             */
            hasSubmittedCertification: boolean;
        };
        AuthTokenResponseDto: {
            /** @description 인증된 유저 정보 */
            user: components["schemas"]["AuthUserDto"];
            /**
             * @description Access Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Refresh Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        RegisterDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호 (8~12자, 특수문자 사용 가능)
             * @example P@ssw0rd!
             */
            password: string;
            /**
             * @description 닉네임
             * @example 김운동
             */
            nickname: string;
            /**
             * @description 전화번호
             * @example 010-1234-5678
             */
            phone?: string;
            /**
             * @description 가입 모드 (미입력 시 customer)
             * @example customer
             * @enum {string}
             */
            mode?: "expert" | "customer";
        };
        LoginDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example P@ssw0rd!
             */
            password: string;
        };
        OAuthTokenResponseDto: {
            /** @description 인증된 유저 정보 */
            user: components["schemas"]["AuthUserDto"];
            /**
             * @description Access Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Refresh Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
            /**
             * @description 신규 가입 여부
             * @example true
             */
            isNewUser: boolean;
        };
        KakaoLoginDto: {
            /**
             * @description 카카오 인가코드
             * @example abc123def456
             */
            code: string;
        };
        AppleLoginDto: {
            /**
             * @description 애플 identityToken (서버에서 서명 검증에 사용)
             * @example eyJraWQiOiJ...
             */
            identityToken: string;
            /**
             * @description 애플 authorizationCode (현재 서버에서 사용하지 않음 — 향후 애플 refresh token 교환용으로 예약)
             * @example c7f9e2d1...
             */
            authorizationCode?: string;
        };
        GoogleLoginDto: {
            /**
             * @description 구글 idToken (Google Sign-In SDK 발급)
             * @example eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            idToken: string;
        };
        TokenRefreshResponseDto: {
            /**
             * @description 새 Access Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description 새 Refresh Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        RefreshTokenDto: {
            /**
             * @description Refresh Token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        MessageResponseDto: {
            /**
             * @description 결과 메시지
             * @example 로그아웃되었습니다.
             */
            message: string;
        };
        WithdrawDto: {
            /**
             * @description 비밀번호 (소셜 로그인 사용자는 불필요)
             * @example P@ssw0rd!
             */
            password?: string;
        };
        CertificationResponseDto: {
            /**
             * @description 자격증 ID
             * @example 1
             */
            id: number;
            /**
             * @description 종류
             * @example physical_therapist
             * @enum {string}
             */
            type: "physical_therapist" | "health_exercise_manager" | "graduation_certificate" | "other";
            /**
             * @description 검수 상태
             * @example pending
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected";
            /**
             * @description 파일 URL 목록
             * @example [
             *       "https://cdn.example.com/cert/1.jpg"
             *     ]
             */
            fileUrls: string[];
            /**
             * Format: date-time
             * @description 검수 완료일
             * @example 2024-02-01T10:00:00.000Z
             */
            reviewedAt?: string;
        };
        CreateCertificationDto: {
            /**
             * @description 자격증 종류
             * @example license
             * @enum {string}
             */
            type?: "license" | "graduation";
            /**
             * @description 자격증 세부 종류 (type=license 시)
             * @example PT
             * @enum {string}
             */
            licenseType?: "PT" | "healthExercise";
        };
        UpdateCertificationStatusDto: {
            /**
             * @description 검수 결과
             * @example approved
             * @enum {string}
             */
            status: "approved" | "rejected";
            /**
             * @description 반려 사유 (rejected 시)
             * @example 이미지가 불명확합니다.
             */
            rejectReason?: string;
        };
        ExpertProfileResponseDto: {
            /**
             * @description 명인 프로필 ID
             * @example 1
             */
            id: number;
            /**
             * @description 유저 ID
             * @example 1
             */
            userId: number;
            /**
             * @description 활동 지역
             * @example 서울 강남구
             */
            region: string;
            /**
             * @description 센터명
             * @example 강남 스포츠 클리닉
             */
            centerName: string;
            /**
             * @description 대표 서비스
             * @example 재활 트레이닝
             */
            representativeService: string;
            /**
             * @description 소개 텍스트
             * @example 10년 경력의 재활 전문 트레이너입니다.
             */
            introduction?: string;
            /**
             * @description 카카오 오픈채팅 URL
             * @example https://open.kakao.com/o/example
             */
            kakaoOpenChatUrl?: string;
            /**
             * @description 등급
             * @example gold
             * @enum {string}
             */
            expertGrade?: "bronze" | "silver" | "gold" | "platinum" | "diamond";
            /**
             * @description 총 리뷰 수
             * @example 42
             */
            totalReviewCount: number;
            /**
             * @description 평균 별점
             * @example 4.8
             */
            averageRating: number;
            /**
             * @description 자격증 검수 상태
             * @example approved
             * @enum {string}
             */
            certificationStatus: "pending" | "approved" | "rejected";
            /**
             * @description 소개 이미지 URL 목록 (최대 5장)
             * @example [
             *       "https://cdn.example.com/img/1.jpg"
             *     ]
             */
            portfolioImageUrls?: string[];
            /**
             * @description 키워드 태그 목록
             * @example [
             *       "재활",
             *       "골프"
             *     ]
             */
            keywordTags?: string[];
            /**
             * @description 경력 텍스트
             * @example 2018-현재 강남 스포츠 클리닉 원장
             */
            careerText?: string;
            /**
             * @description 학력 PDF URL
             * @example https://cdn.example.com/edu/1.pdf
             */
            educationPdfUrl?: string;
            /**
             * Format: date-time
             * @description 생성일
             * @example 2024-01-15T09:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 수정일
             * @example 2024-06-01T12:00:00.000Z
             */
            updatedAt: string;
        };
        ReviewTokenResponseDto: {
            /**
             * @description 리뷰 요청 토큰
             * @example abc123reviewtoken
             */
            reviewToken: string;
            /**
             * @description 딥링크 URL
             * @example sportsmaster://review?token=abc123reviewtoken
             */
            deepLink: string;
        };
        CreateReviewTokenDto: {
            /**
             * @description 채팅방 ID
             * @example 1
             */
            chatRoomId: number;
        };
        DiagnosisCustomerProfileDto: {
            /**
             * @description 지역
             * @example 서울 강남구
             */
            region: string;
            /**
             * @description 성별
             * @example male
             * @enum {string}
             */
            gender?: "male" | "female" | "other";
            /**
             * @description 이름
             * @example 김고객
             */
            name: string;
            /**
             * @description 나이
             * @example 28
             */
            age?: number;
            /**
             * @description 운동종목
             * @example 골프
             */
            sport?: string;
            /**
             * @description 개인 코드
             * @example USR-000003
             */
            personalCode: string;
        };
        DiagnosisIncomingItemDto: {
            /**
             * @description 진단요청 ID
             * @example 1
             */
            id: number;
            /** @description 고객 프로필 요약 */
            customerProfile: components["schemas"]["DiagnosisCustomerProfileDto"];
            /**
             * Format: date-time
             * @description 요청일
             * @example 2024-06-01T09:00:00.000Z
             */
            createdAt: string;
        };
        UpdateModeResponseDto: {
            /**
             * @description 변경된 모드
             * @example expert
             * @enum {string}
             */
            currentMode: "expert" | "customer";
            /**
             * @description 모드를 명시적으로 확정했는지 여부
             * @example true
             */
            hasSelectedMode: boolean;
        };
        UpdateModeDto: {
            /**
             * @description 전환할 모드
             * @example expert
             * @enum {string}
             */
            mode: "expert" | "customer";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["AuthTokenResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["AuthTokenResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_kakaoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KakaoLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["OAuthTokenResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_appleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppleLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["OAuthTokenResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["OAuthTokenResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["TokenRefreshResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["MessageResponseDto"];
                    };
                };
            };
        };
    };
    AuthController_withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["MessageResponseDto"];
                    };
                };
            };
        };
    };
    CertificationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["CertificationResponseDto"][];
                    };
                };
            };
        };
    };
    CertificationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateCertificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["CertificationResponseDto"];
                    };
                };
            };
        };
    };
    CertificationsController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["CertificationResponseDto"][];
                    };
                };
            };
        };
    };
    CertificationsController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCertificationStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["CertificationResponseDto"];
                    };
                };
            };
        };
    };
    HomeController_getExpertGrade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["ExpertProfileResponseDto"];
                    };
                };
            };
        };
    };
    HomeController_createReviewRequestLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["ReviewTokenResponseDto"];
                    };
                };
            };
        };
    };
    HomeController_getDiagnosisPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["DiagnosisIncomingItemDto"][];
                    };
                };
            };
        };
    };
    HomeController_switchMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDto"] & {
                        data?: components["schemas"]["UpdateModeResponseDto"];
                    };
                };
            };
        };
    };
}
