export const MOCK_DIAGNOSIS_REQUESTS = [
  {
    id: 1,
    status: 'pending',
    isViewed: false,
    customerProfile: {
      personalCode: 'USR-000001',
      nickname: '달리기왕',
      profileImageUrl: null,
      name: '김지훈',
      age: 28,
      gender: 'male',
      region: '서울 강남구',
      sport: '달리기',
      keywordTags: ['무릎 통증', '자세 교정', '근력 향상'],
      introduction: '주 3회 달리기를 하는데 무릎이 자주 아파요. 올바른 자세와 훈련법이 궁금합니다.',
    },
    createdAt: '2025-07-01T09:00:00Z',
  },
  {
    id: 4,
    status: 'pending',
    isViewed: true,
    customerProfile: {
      personalCode: 'USR-000004',
      nickname: '요가마스터',
      profileImageUrl: null,
      name: '최유진',
      age: 31,
      gender: 'female',
      region: '서울 마포구',
      sport: '요가',
      keywordTags: ['유연성', '코어 강화', '명상'],
      introduction: '요가를 5년째 하고 있는데, 더 깊은 수련을 원합니다.',
    },
    createdAt: '2025-07-04T08:30:00Z',
  },
  {
    id: 5,
    status: 'pending',
    isViewed: false,
    customerProfile: {
      personalCode: 'USR-000005',
      nickname: null,
      profileImageUrl: null,
      name: '정태양',
      age: 45,
      gender: 'male',
      region: '인천 연수구',
      sport: '골프',
      keywordTags: ['스윙 교정'],
      introduction: null,
    },
    createdAt: '2025-07-05T14:00:00Z',
  },
  {
    id: 6,
    status: 'pending',
    isViewed: false,
    customerProfile: {
      personalCode: 'USR-000006',
      nickname: null,
      profileImageUrl: null,
      name: '한서연',
      age: 27,
      gender: 'female',
      region: '광주 서구',
      sport: '필라테스',
      keywordTags: null,
      introduction: null,
    },
    createdAt: '2025-07-06T16:00:00Z',
  },
]
